files:
  include:
    - ./index.html
    - ./app/test.html
    - ./app/app.component.html

rules:
  include:
    - all

reporter:
  type: sonarqube
  outputDir: ./dist/reports
  projectKey: my-project-key
  serverUrl: http://localhost:9000
  login: $SONAR_TOKEN
