name: Deploy Angular to GitHub Pages with JFrog Auth

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Limpiar credenciales heredadas de npm
        run: |
          echo "Eliminando posibles credenciales heredadas..."
          rm -f ~/.npmrc
          rm -f ~/.npm/_auth.json
          unset NPM_TOKEN

      - name: Configurar autenticación JFrog y registry público
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "@saffron:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/" >> ~/.npmrc
          echo "//tr1.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.ARTIFACTORY_TOKEN_TR }}" >> ~/.npmrc
          echo "//tr1.jfrog.io/artifactory/api/npm/npm/:always-auth=true" >> ~/.npmrc

      - name: Verificar .npmrc generado
        run: |
          echo "Contenido de .npmrc:"
          cat ~/.npmrc | sed 's/_authToken=.*/_authToken=*** (oculto)/'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar proyecto Angular
        run: ng build --output-path docs --base-href /pablo-sand-box/

      - name: Desplegar en gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
