name: Deploy Angular to GitHub Pages with JFrog Auth

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure JFrog Artifactory auth
        run: |
          echo "//artifactory.example.com/artifactory/api/npm/npm/:_authToken=${{ secrets.JFROG_TOKEN }}" > .npmrc
          echo "registry=https://artifactory.example.com/artifactory/api/npm/npm/" >> .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: ng build --output-path dist --base-href /secure-sand-box/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
