name: Deploy Angular to GitHub Pages with JFrog (limpio, debug)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Print environment info (debug)
        run: |
          echo "USER: $USER"
          echo "HOME: $HOME"
          echo "PWD: $PWD"
          node -v
          npm -v
          env | sort

      - name: Backup and remove global .npmrc (si existe)
        run: |
          if [ -f $HOME/.npmrc ]; then
            echo "Moviendo $HOME/.npmrc a $HOME/.npmrc.backup"
            mv $HOME/.npmrc $HOME/.npmrc.backup
          else
            echo "No hay .npmrc global en $HOME"
          fi

      - name: Prepara .npmrc local para JFrog
        run: |
          echo "//tr1.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.JFROG_AUTH_TOKEN }}" > .npmrc
          echo "@saffron:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/" >> .npmrc
          echo "registry=https://tr1.jfrog.io/artifactory/api/npm/npm/" >> .npmrc

      - name: Show .npmrc (sin token)
        run: cat .npmrc | grep -v _authToken

      - name: Show npm config
        run: npm config ls

      - name: Try npm whoami (verifica login)
        run: npm whoami || echo "NPM whoami falló"

      - name: Busca referencias a agora.dequecloud.com en el lockfile
        run: |
          if grep -q "agora.dequecloud.com" package-lock.json; then
            echo "¡Referencia encontrada! Limpiando lockfile y node_modules..."
            rm -rf node_modules package-lock.json
            npm install
          else
            echo "No hay referencias a agora.dequecloud.com en package-lock.json"
          fi

      - name: Install dependencies (con debug)
        run: npm ci --loglevel verbose

      - name: Build Angular project
        run: ng build --output-path docs --base-href /pablo-sand-box/

      - name: List build output (debug)
        run: ls -lh docs || echo "No se generó docs"

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs