name: CI Install JFrog & Agora Packages Without .npmrc

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install @axe-devtools/axe-linter-connector from Agora
        env:
          "npm_config_@axe-devtools:registry": "https://agora.dequecloud.com/artifactory/api/npm/devtools-npm/"
          "npm_config_//agora.dequecloud.com/artifactory/api/npm/devtools-npm/:_auth": ${{ secrets.AGORA_NPM_AUTH }}
          "npm_config_//agora.dequecloud.com/artifactory/api/npm/devtools-npm/:email": ${{ secrets.NPM_EMAIL }}
          "npm_config_//agora.dequecloud.com/artifactory/api/npm/devtools-npm/:always-auth": "true"
        run: |
          npm install @axe-devtools/axe-linter-connector --registry=https://agora.dequecloud.com/artifactory/api/npm/devtools-npm/
        working-directory: ./pablo-sand-box

      - name: Install dependencies from JFrog
        env:
            "npm_config_registry": "https://tr1.jfrog.io/artifactory/api/npm/npm/"
            "npm_config_//tr1.jfrog.io/artifactory/api/npm/npm/:_authToken": ${{ secrets.JFROG_AUTH_TOKEN }}
            "npm_config_//tr1.jfrog.io/artifactory/api/npm/npm/:always-auth": "true"
        run: npm ci
        working-directory: ./pablo-sand-box

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./pablo-sand-box
      
      - name: Build Angular project
        run: ng build --output-path docs --base-href /secure-sand-box/
        working-directory: ./pablo-sand-box


      - name: Build React project (Next.js static export)
        run: |
          if [ -d ./pablo-sand-box/checkbox-ui ]; then
            cd ./pablo-sand-box/checkbox-ui
            npm install || true
            npm run build || true
            if [ -d out ]; then
              # Copia index.html a 404.html para soportar rutas internas en GitHub Pages
              cp out/index.html out/404.html
              DOCS_PATH="${{ github.workspace }}/pablo-sand-box/docs/checkbox-ui"
              rm -rf "$DOCS_PATH"
              mkdir -p "$DOCS_PATH"
              cp -a out/. "$DOCS_PATH/"
              echo "Exported static site copied to $DOCS_PATH."
            else
              echo "No out/ directory generated by Next.js export."
            fi
            cd -
          else
            echo "React folder not found, skipping build."
          fi

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && success()
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GH_PAGES_TOKEN }}
            publish_dir: ./pablo-sand-box/docs
            publish_branch: gh-pages



  delete-branch:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch after PR merge (except main, master, gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          REPO: ${{ github.repository }}
        run: |
          if [[ "$BRANCH" != "main" && "$BRANCH" != "master" && "$BRANCH" != "gh-pages" ]]; then
            echo "Deleting branch $BRANCH from $REPO"
            curl -s -X DELETE \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH
          else
            echo "Not deleting protected branch: $BRANCH"
          fi