name: Deploy Angular to GitHub Pages with JFrog Auth

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Borrar .npmrc global temporalmente
        run: |
          mv ~/.npmrc ~/.npmrc.bak || true

      - name: Configure JFrog Artifactory auth
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "@saffron:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/" >> ~/.npmrc
          echo "//tr1.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.ARTIFACTORY_TOKEN_TR }}" >> ~/.npmrc
          echo "//tr1.jfrog.io/artifactory/api/npm/npm/:always-auth=true" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=" >> ~/.npmrc

      - name: Verificar .npmrc generado
        run: |
          echo "Contenido de .npmrc:"
          cat ~/.npmrc | sed 's/_authToken=.*/_authToken=*** (oculto)/'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: ng build --output-path docs --base-href /pablo-sand-box/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages

