name: CI JFrog + Agora

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted  # O usa ubuntu-latest según tu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate .npmrc for JFrog & Agora
        run: |
          cat <<'EOF' > .npmrc
            @208177:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/
            @dcl:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/
            @dcl-ue:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/
            @saffron:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/
            @tr:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/
            @tr-digital:registry=https://tr1.jfrog.io/artifactory/api/npm/npm/
            registry=https://tr1.jfrog.io/artifactory/api/npm/npm/
            //tr1.jfrog.io/artifactory/api/npm/npm/:_authToken=${{ secrets.JFROG_AUTH_TOKEN }}
            //tr1.jfrog.io/artifactory/api/npm/npm/:always-auth=true
            @axe-devtools:registry=https://agora.dequecloud.com/artifactory/api/npm/devtools-npm/
            //agora.dequecloud.com/artifactory/api/npm/devtools-npm/:_auth=${{ secrets.AGORA_NPM_AUTH }}
            //agora.dequecloud.com/artifactory/api/npm/devtools-npm/:email=${{ secrets.NPM_EMAIL }}
            //agora.dequecloud.com/artifactory/api/npm/devtools-npm/:always-auth=true
            EOF

      - name: Show .npmrc (debug, no secrets)
        run: cat .npmrc | grep -v _auth | grep -v email

      - name: Install dependencies
        run: npm ci

      - name: Build/test/other steps
        run: echo "Aquí irían tus comandos de build, test, lint, etc."