name: Test GitHub Actions

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "✅ GitHub Actions está funcionando correctamente"

      - name: Usar token de GitHub
        run: echo "Token disponible"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
