name: Test desde PR externo

on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "✅ Workflow ejecutado desde pull_request_target"
