name: Test GitHub Actions

on:
  push:
    branches:
      - feat-axe-linter-add

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "✅ GitHub Actions está funcionando correctamentes"
